### ISSUE TITLE
Your traits have wonky descriptions

### ISSUE THREAD

**Issue by Konrad22** [doofus-01/wesnoth-Bad_Moon_Rising#2]
fast-hand
_unit is has_...

lethal
_unit is has_...

stoic
_unit is has_ higher resistance to all attacks and higher hitpoints.
+12 hp

massive
_unit is has_...
weapon: +2 dmg
+8 hp

Both descriptions are missing some kind of +x type resistance.
'massive' also lacks a period to end the description (inconsistent with the other 2 traits you made)

**Comment by doofus-01** [comment]
This was an <i>Archaic Resources</i> issue.  I believe this "is has" stuff is fixed.
(Thanks.)
