### ISSUE TITLE
The Pit - Revisited, enemy flag isn't visible

### ISSUE THREAD

**Issue by Konrad22** [doofus-01/wesnoth-Bad_Moon_Rising#4]
As it says. The village belongs to the enemy, but I can't see that without hovering with the mouse over the village to read 'Enemy village'.
[BMR3-The Pit - Revisited-Auto-Save18.gz](https://github.com/doofus-01/wesnoth-Bad_Moon_Rising/files/2951571/BMR3-The.Pit.-.Revisited-Auto-Save18.gz)

**Comment by doofus-01** [comment]
Is this a scenario that was started in an older campaign version, then continued on the current one?

**Comment by doofus-01** [comment]
see #6
